<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateStatsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('stats', function (Blueprint $table) {
            $table->integer('Stats_id')->nullable();
            $table->longText('Event')->nullable();
            $table->double('LapNumber')->nullable();
            $table->longText('Driver')->nullable();
            $table->longText('Session')->nullable();
            $table->double('TimeDay')->nullable();
            $table->double('Run')->nullable();
            $table->double('Lap')->nullable();
            $table->double('LapTime')->nullable();
            $table->double('Car')->nullable();
            $table->longText('DriverEnd')->nullable();
            $table->longText('Session_Description')->nullable();
            $table->double('tLift')->nullable();
            $table->double('vCar')->nullable();
            $table->double('PDischargeMax')->nullable();
            $table->double('PChargeMax')->nullable();
            $table->double('TBrakeFL')->nullable();
            $table->double('TBrakeFR')->nullable();
            $table->double('TBrakeRL')->nullable();
            $table->double('TBrakeRR')->nullable();
            $table->double('pBrakeF')->nullable();
            $table->double('pBrakeBBWCaliper')->nullable();
            $table->double('CAR_A_USOS_CORNER')->nullable();
            $table->double('CAR_A_USOS_HS')->nullable();
            $table->double('CAR_A_USOS_MS')->nullable();
            $table->double('CAR_A_USOS_LS')->nullable();
            $table->double('CAR_G_AX_BRAKE_KPI')->nullable();
            $table->double('TBrakeCoolingFL')->nullable();
            $table->double('TBrakeCoolingFR')->nullable();
            $table->double('TBrakeCoolingRL')->nullable();
            $table->double('TBrakeCoolingRR')->nullable();
            $table->double('rMBrakeBalance')->nullable();
            $table->double('PRESSFIAMin')->nullable();
            $table->double('PRESSFIAMax')->nullable();
            $table->double('TTyreCarcassFL')->nullable();
            $table->double('TTyreCarcassFR')->nullable();
            $table->double('TTyreCarcassRL')->nullable();
            $table->double('TTyreCarcassRR')->nullable();
            $table->double('TYR_T_SPLIT_MAX')->nullable();
            $table->double('pTyreFL')->nullable();
            $table->double('pTyreFR')->nullable();
            $table->double('pTyreRL')->nullable();
            $table->double('pTyreRR')->nullable();
            $table->double('TYR_SLIP_R_ENTRY_FA')->nullable();
            $table->double('TYR_SLIP_R_ENTRY_RA')->nullable();
            $table->double('TYR_SPIN')->nullable();
            $table->double('TYR_LOCK_FA_EOL')->nullable();
            $table->double('TYR_LOCK_RA_EOL')->nullable();
            $table->double('TYR_LOCK_BIAS_EOL')->nullable();
            $table->double('TYR_ENERGY_FXY_BIAS')->nullable();
            $table->double('TYR_ENERGY_FXYFA')->nullable();
            $table->double('TYR_ENERGY_FXYRA')->nullable();
            $table->double('TYR_ENERGY_FXYFL')->nullable();
            $table->double('TYR_ENERGY_FXYFR')->nullable();
            $table->double('TYR_ENERGY_FXYRL')->nullable();
            $table->double('TYR_ENERGY_FXYRR')->nullable();
            $table->double('TYR_GRIPX_FA')->nullable();
            $table->double('TYR_GRIPX_RA')->nullable();
            $table->double('TYR_GRIPY_FA')->nullable();
            $table->double('TYR_GRIPY_RA')->nullable();
            $table->double('ROL_X_BIAS_AVG')->nullable();
            $table->double('TYR_AYMAX')->nullable();
            $table->double('STIFF_ROL_FA')->nullable();
            $table->double('STIFF_ROL_RA')->nullable();
            $table->double('ETotalFIA')->nullable();
            $table->double('EDischargeRESS')->nullable();
            $table->double('EChargeRESS')->nullable();
            $table->double('EChargeBrake')->nullable();
            $table->double('EChargeBrakeOnly')->nullable();
            $table->double('EChargePaddleOnly')->nullable();
            $table->double('EChargeBrakePaddle')->nullable();
            $table->double('EQualiPowerExceeded')->nullable();
            $table->double('ERacePowerExceeded')->nullable();
            $table->double('EFanBoostPowerExceeded')->nullable();
            $table->double('PThrottleFIALimitMax')->nullable();
            $table->double('PThrottleFIALimitMin')->nullable();
            $table->double('RHL_X_FA_Setup')->nullable();
            $table->double('RHL_X_RA_Setup')->nullable();
            $table->double('TYR_BRAKE_EFF_FA')->nullable();
            $table->double('TYR_BRAKE_EFF_RA')->nullable();
            $table->double('TYR_ENERGY_FXRA_EOL_PADDLE')->nullable();
            $table->double('ELapConsumptionSFLine')->nullable();
            $table->double('ELapConsumptionTarget')->nullable();
            $table->double('PPTEMIntervention')->nullable();
            $table->double('NTEM_Intensity_C')->nullable();
            $table->double('PTEM_Intensity_C')->nullable();
            $table->double('EBrakeF')->nullable();
            $table->double('EBrakeR')->nullable();
            $table->double('gLong_BrakeEff_Intensity')->nullable();
            $table->double('gLong_NRJBrakeEfficiency_AVG')->nullable();
            $table->double('Time_cdBrakeLat')->nullable();
            $table->double('Time_cdPaddleLat')->nullable();
            $table->double('Time_cdThrottleLat')->nullable();
            $table->double('EChargePaddle')->nullable();
            $table->double('TYR_LOCK_RA_NoPaddle_EOL')->nullable();
            $table->double('PowerAverageHighSpeed')->nullable();
            $table->double('PowerAverageLowSpeed')->nullable();
            $table->double('PowerAverageMediumSpeed')->nullable();
            $table->double('PowertrainNoiseIntegral')->nullable();

            $table->charset = 'latin1';
            $table->collation = 'latin1_swedish_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('stats');
    }
}
