<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateLapsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('laps', function (Blueprint $table) {
            $table->integer('Lap_ID')->nullable();
            $table->integer('Session_ID')->nullable();
            $table->integer('Driver_ID')->nullable();
            $table->integer('Stats_ID')->nullable();
            $table->integer('Radio_ID')->nullable();
            $table->double('S1Time')->nullable();
            $table->double('S2Time')->nullable();
            $table->double('S3Time')->nullable();
            $table->double('Laptime')->nullable();
            $table->double('BestS1Time')->nullable();
            $table->double('BestS2Time')->nullable();
            $table->double('BestS3Time')->nullable();
            $table->double('BestLaptime')->nullable();
            $table->double('GapPrev')->nullable();
            $table->double('GapNext')->nullable();
            $table->double('GapFirst')->nullable();
            $table->integer('GPS_ID')->nullable();
            $table->integer('Flag_ID')->nullable();
            $table->double('SOC_TV')->nullable();
            $table->integer('LapNumber')->nullable();
            $table->string('Laptime_T', 16)->nullable()->charset('utf8')->collation('utf8_general_ci');
            $table->string('S1_T', 16)->nullable()->charset('utf8')->collation('utf8_general_ci');
            $table->string('S2_T', 16)->nullable()->charset('utf8')->collation('utf8_general_ci');
            $table->string('S3_T', 16)->nullable()->charset('utf8')->collation('utf8_general_ci');
            $table->integer('Team_ID')->nullable();
            $table->string('Elapsed', 16)->nullable()->charset('utf8')->collation('utf8_general_ci');
            $table->double('Speed_Avg')->nullable();
            $table->char('Crossing_Line', 10)->nullable()->charset('utf8')->collation('utf8_general_ci');
            $table->double('TopSpeed')->nullable();
            $table->double('Power')->nullable();
            $table->string('Pit_Time', 16)->nullable()->charset('utf8')->collation('utf8_general_ci');
            $table->integer('Run_ID')->nullable();
            $table->double('SOC')->nullable();
            $table->double('ELap')->nullable();
            $table->double('ERemaining')->nullable();

            $table->charset = 'latin1';
            $table->collation = 'latin1_swedish_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('laps');
    }
}
