<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateSetupsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('setups', function (Blueprint $table) {
            $table->integer('Setup_ID')->nullable();
            $table->integer('Run_ID')->nullable();
            $table->longText('SetupName')->nullable();
            $table->double('Air_Temperature')->nullable();
            $table->double('AirDensity')->nullable();
            $table->double('Air_Pressure')->nullable();
            $table->double('AB')->nullable();
            $table->double('MB')->nullable();
            $table->double('CarB')->nullable();
            $table->double('EOS_RH_Keel')->nullable();
            $table->double('Speed')->nullable();
            $table->double('RefSpeed')->nullable();
            $table->double('KEEL')->nullable();
            $table->double('Ballast_Weight')->nullable();
            $table->double('Car_Weight')->nullable();
            $table->double('Total_Weight')->nullable();
            $table->double('Car_Weight_Repart')->nullable();
            $table->double('Weight_Repart')->nullable();
            $table->double('WFL_WB')->nullable();
            $table->double('Weight_FL')->nullable();
            $table->double('WFR_WB')->nullable();
            $table->double('Weight_FR')->nullable();
            $table->double('WRL_WB')->nullable();
            $table->double('Weight_RL')->nullable();
            $table->double('WRR_WB')->nullable();
            $table->double('Weight_RR')->nullable();
            $table->double('Driver_Weight')->nullable();
            $table->double('ChassisNum')->nullable();
            $table->longText('FW')->nullable();
            $table->double('FRH')->nullable();
            $table->double('RRH')->nullable();
            $table->double('ARB_Stiffness_F')->nullable();
            $table->double('DroopF')->nullable();
            $table->double('Spring_Stiffness_FA')->nullable();
            $table->double('Static_Gap_F')->nullable();
            $table->double('SuspFrontCaster')->nullable();
            $table->double('StiffnessFront')->nullable();
            $table->longText('Table_KIN_R')->nullable();
            $table->double('ARB_Stiffness_R')->nullable();
            $table->double('DroopR')->nullable();
            $table->double('Spring_Stiffness_RA')->nullable();
            $table->double('Spring_Preload_R')->nullable();
            $table->double('Static_Gap_R')->nullable();
            $table->double('StiffnessRear')->nullable();
            $table->longText('Diff_Ramp')->nullable();
            $table->double('Diff_Preload')->nullable();
            $table->double('Diff_Preload_Press')->nullable();
            $table->double('Spring_Stiffness_RA_Preload')->nullable();
            $table->double('Droop_Eq')->nullable();
            $table->double('Droop_Av')->nullable();
            $table->double('Preload_to_ref')->nullable();
            $table->double('Preload_to_ref_conv')->nullable();
            $table->double('Tyre_P_FL')->nullable();
            $table->double('Tyre_P_FR')->nullable();
            $table->double('Tyre_P_RL')->nullable();
            $table->double('Tyre_P_RR')->nullable();
            $table->double('Toe_FL')->nullable();
            $table->double('Toe_FR')->nullable();
            $table->double('Toe_RL')->nullable();
            $table->double('Toe_RR')->nullable();
            $table->double('Camber_FL')->nullable();
            $table->double('Camber_FR')->nullable();
            $table->double('Camber_RL')->nullable();
            $table->double('Camber_RR')->nullable();
            $table->double('F_Bump_LS_S1')->nullable();
            $table->double('F_Bump_HS_S1')->nullable();
            $table->double('F_Rebound_LS_S1')->nullable();
            $table->double('F_Rebound_HS_S1')->nullable();
            $table->double('F_Drop_Off_S1')->nullable();
            $table->double('F_Bump_LS_S2')->nullable();
            $table->double('F_Bump_HS_S2')->nullable();
            $table->double('F_Rebound_LS_S2')->nullable();
            $table->double('F_Rebound_HS_S2')->nullable();
            $table->double('F_Drop_Off_S2')->nullable();
            $table->double('R_Bump_LS_S1')->nullable();
            $table->double('R_Bump_HS_S1')->nullable();
            $table->double('R_Rebound_LS_S1')->nullable();
            $table->double('R_Rebound_HS_S1')->nullable();
            $table->double('R_Drop_Off_S1')->nullable();
            $table->double('R_Bump_LS_S2')->nullable();
            $table->double('R_Bump_HS_S2')->nullable();
            $table->double('R_Rebound_LS_S2')->nullable();
            $table->double('R_Rebound_HS_S2')->nullable();
            $table->double('R_Drop_Off_S2')->nullable();
            $table->longText('NameFrontSetup1')->nullable();
            $table->longText('NameFrontSetup2')->nullable();
            $table->longText('NameRearSetup1')->nullable();
            $table->longText('NameRearSetup2')->nullable();

            $table->charset = 'latin1';
            $table->collation = 'latin1_swedish_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('setups');
    }
}
